insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("LG 그램", "노트북", 150, "LG 전자", 1000, "가벼워요")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("아이폰 11", "휴대폰", 105, "애플", 20, "연보라 색상")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("냉장고", "가전", 97, "삼성", 300, "양문형")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("에어컨", "가전", 136, "LG 전자", 300, "인공 지능 기능 탑재")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("맥북", "노트북", 319, "애플", 500, "2019년형")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("세탁기", "가전", 42, "LG 전자", 800, "용량 14kg")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("아이폰 8", "휴대폰", 59, "애플", 200, "홈버튼 있어요")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("슬리퍼", "잡화", 3, "버켄스탁", 5000, "방수")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("조깅화", "잡화", 10, "아디다스", 3000, "여성용 초경량")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("양말", "잡화", 1, "나이키", 9000, "스포츠 양말")